#!/bin/bash
# ToolVerse Deployment Guide

echo "🚀 ToolVerse Deployment Guide"
echo "=============================="
echo ""

echo "📋 ADIM 1: VERCEL FRONTEND DEPLOY"
echo "1. https://vercel.com'a git hub hesabınla giriş yap"
echo "2. 'Add New' > 'Project' tıkla"
echo "3. 'umutcodde/toolverse' reposunu seç"
echo "4. Deploy et"
echo "Vercel URL'i not et (örn: https://toolverse-tau.vercel.app)"
echo ""

echo "📋 ADIM 2: BACKEND SETUP (Lokal)"
echo "1. 'backend' klasörüne git: cd backend"
echo "2. Modülleri kur: npm install"
echo "3. .env dosyası oluştur:"
echo "   cp .env.example .env"
echo "4. .env'i doldur:"
echo "   - DATABASE_URL (Neon/Supabase'den)"
echo "   - JWT_SECRET (openssl rand -hex 64)"
echo "   - SMTP_* (Resend veya Mailgun)"
echo "   - FRONTEND_URL=https://toolverse-tau.vercel.app"
echo ""

echo "📋 ADIM 3: DATABASE OLUŞTUR"
echo "1. PostgreSQL sağlayıcı seç:"
echo "   - Neon (https://neon.tech) - Ücretsiz, önerilen"
echo "   - Supabase (https://supabase.com)"
echo "2. Yeni database oluştur 'toolverse'"
echo "3. Connection string'i kopyala"
echo "4. .env'de DATABASE_URL olarak yapıştır"
echo "5. SQL şemasını çalıştır:"
echo "   psql \"<DATABASE_URL>\" < backend/db/init.sql"
echo ""

echo "📋 ADIM 4: BACKEND DEPLOY (Render)"
echo "1. https://render.com'a git (ücretsiz)"
echo "2. 'New +' > 'Web Service'"
echo "3. GitHub repo bağla (umutcodde/toolverse)"
echo "4. Ayarlar:"
echo "   - Name: toolverse-api"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "5. Environment Variables ekle (.env dosyasından)"
echo "6. Deploy et"
echo "Render URL'i not et (https://toolverse-api.onrender.com)"
echo ""

echo "📋 ADIM 5: VERCEL'E BACKEND URL EKLE"
echo "1. Vercel Dashboard > Project Settings > Environment Variables"
echo "2. Yeni Variable ekle:"
echo "   REACT_APP_API_URL = https://toolverse-api.onrender.com"
echo "3. Redeploy et"
echo ""

echo "📋 ADIM 6: EMAIL SETUP (Resend)"
echo "1. https://resend.com'a git (ücretsiz)"
echo "2. API key al"
echo "3. Backend .env'de SMTP_* bilgilerini doldur"
echo ""

echo "✅ HEPSI TAMAMSA:"
echo "Frontend: https://toolverse-tau.vercel.app"
echo "Backend: https://toolverse-api.onrender.com"
echo "Database: Neon PostgreSQL"
echo "Emails: Resend"
echo ""
echo "🎉 Tamamlandı!"
